version: '3.10'

services:
  payment_db:
    container_name: payment_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=root", "--password=root", "--execute", "SHOW DATABASES;"]
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  mysql-data:
