version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: fiap-fase3-app
    ports:
      - "5050:5050"
    links:
      - mongo