apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
spec:
  selector:
    app: payment-microservice
  ports:
    - protocol: TCP
      containerPort: 5050
  type: LoadBalancer